### ISSUE TITLE
Remote machine shouldn't need to have covalent installed

### ISSUE THREAD

**Issue by jkanem** [AgnostiqHQ/covalent-slurm-plugin#11]
### Environment

- **Covalent version**: 0.77.0
- **Covalent-Slurm plugin version**: 0.2.1
- **Python version**: 3.8.13
- **Operating system**: Ubuntu 21.10

### What is happening?

The function to be executed is sent to the remote machine as a Covalent `TransportableObject` object. Which needs to be deserialized on the remote machine in order to run, which requires a Covalent installation on the remote machine. If the deserialized function is sent instead, a "vanilla" python installation would be able to execute the function.

### How can we reproduce the issue?

Run a simple workflow where the remote machine does not have Covalent installed. It will not succeed.

### What should happen?

The function execution should happen regardless of if Covalent is installed on the remote machine.

### Any suggestions?

Early in the `execute` method, the function should be deserialized before sending to the remote machine:
`function = function.get_deserialized()`

**Comment by venkatBala** [comment]
Tasks have also been failing due to `ModuleNotFoundError` for `covalent-slurm-plugin`

**Comment by arosen93** [comment]
With covalent==0.209.1 and covalent-slurm-plugin==0.8.0, I am still getting `ModuleNotFoundError: No module named 'covalent'` on the remote machine when covalent isn't installed. The issue resolves once covalent is installed in the remote machine's Python environment.
