### ISSUE TITLE
Add support for a certificate file to be passed to `asyncssh.connect()`

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent-slurm-plugin#45]
### What should we add?

Currently, `client_keys` in `asyncssh.connect()` is set to `client_keys=[self.ssh_key_file]`, and `self.ssh_key_file` is coded such that it can only be a single path, as shown below.

https://github.com/AgnostiqHQ/covalent-slurm-plugin/blob/f48c03d6781f0e314aa0921a65b6228112310287/covalent_slurm_plugin/slurm.py#L129-L135

However, some supercomputers require a `list[tuple(str, str)]` to be passed that has the SSH key and a certificate file, respectively. For an example, [here](https://github.com/NERSC/jupyterhub-deploy/blob/021ccbef046adaf5bcd4602105d89942f06df769/jupyter-nersc/web-jupyterhub/jupyterhub_config.py#L1247-L1253) is the necessary approach to `asyncssh.connect` to a U.S. DOE cluster at NERSC. Two filepaths in a tuple are needed, but it's not possible for this to be set right now. There is also no way in the current code to set `client_keys=None` explicitly, which ignores authentication, but that's less important since I imagine most people are (or should) be using SSH keys.

In general, I think some additional flexibility in what can be passed to `asyncssh.connect()` would help ensure that the plugin is useful for a wide range of HPC machines.

-----

As a side-note, I don't think it's possible for `_client_connect()` to ever actually return `False` for `ssh_success` based on the code below, although that's not really a major concern.

https://github.com/AgnostiqHQ/covalent-slurm-plugin/blob/f48c03d6781f0e314aa0921a65b6228112310287/covalent_slurm_plugin/slurm.py#L116-L143

### Describe alternatives you've considered.

There is no alternative. See PR in #47.

**Comment by arosen93** [comment]
Never mind! I see this is taken care of with the `prerun_commands` and `postrun_commands` described [here](https://covalent.readthedocs.io/en/latest/api/executors/slurm.html).

It would likely be worthwhile to link to the slurm executor API page from the README to orient users in the right direction, but I'll close this one!

**Comment by santoshkumarradha** [comment]
🔥
