### ISSUE TITLE
Slurm sublattice fails with "username is a required parameter in the Slurm plugin."

### ISSUE THREAD

**Issue by jackbaker1001** [AgnostiqHQ/covalent-slurm-plugin#70]
### Environment

- **Covalent version**:  0.220.0
- **Covalent-Slurm plugin version**: 0.16.0
- **Python version**: 3.8.16
- **Operating system**: MacOS Ventura 13.3.1

### What is happening?

Calling a Slurm sublattice within a base (Dask) lattice fails with the traceback:

```
Traceback (most recent call last):
File "/Users/jbaker/miniconda3/envs/covalent_slurm/lib/python3.8/site-packages/covalent_dispatcher/_core/runner.py", line 251, in _run_task
output, stdout, stderr, status = await executor._execute(
File "/Users/jbaker/miniconda3/envs/covalent_slurm/lib/python3.8/site-packages/covalent/executor/base.py", line 628, in _execute
return await self.execute(
File "/Users/jbaker/miniconda3/envs/covalent_slurm/lib/python3.8/site-packages/covalent/executor/base.py", line 657, in execute
result = await self.run(function, args, kwargs, task_metadata)
File "/Users/jbaker/code/covalent/covalent-slurm-plugin/covalent_slurm_plugin/slurm.py", line 623, in run
conn = await self._client_connect()
File "/Users/jbaker/code/covalent/covalent-slurm-plugin/covalent_slurm_plugin/slurm.py", line 213, in _client_connect
raise ValueError("username is a required parameter in the Slurm plugin.")
ValueError: username is a required parameter in the Slurm plugin.
```

Despite the username being defined in the supplied `ct.executor.SlurmExecutor` object.

### How can we reproduce the issue?

The below code (very similar to [69](https://github.com/AgnostiqHQ/covalent-slurm-plugin/issues/69)) reproduces the issue:

```python

import covalent as ct
import numpy as np

executor = ct.executor.SlurmExecutor(
       remote_workdir="<wdir>",
       options={
           "qos": "regular",
           "t": "00:05:00",
           "nodes": 1,
           "C": "gpu",
           "A": "<acc code>",
           "J": "bug_test",
           "ntasks-per-node": 4,
           "gpus-per-task": 1,
           "gpu-bind": "map_gpu:0,1,2,3"
       },
       prerun_commands=[
           "export COVALENT_CONFIG_DIR="<somewhere in scratch>",
           "export COVALENT_CACHE_DIR="<somewhere in scratch>",
           "export SLURM_CPU_BIND=\"cores\"",
           "export OMP_PROC_BIND=spread",
           "export OMP_PLACES=threads",
           "export OMP_NUM_THREADS=1",
       ],
       username="<username>",
       ssh_key_file="<key>",
       cert_file="<cert>",
       address="perlmutter-p1.nersc.gov",
       conda_env="<conda env>",
       use_srun=False
)

@ct.electron
def get_rand_sum_length(lo, hi):
    np.random.seed(1984)
    return np.random.randint(lo, hi)

@ct.electron
def get_rand_num_slurm(lo, hi):
    np.random.seed(1984)
    return np.random.randint(lo, hi)  

# Slurm sublattice
@ct.electron
@ct.lattice(executor=executor, workflow_executor=executor)
def add_n_random_nums(n, lo, hi):
    np.random.seed(1984)
    sum = 0
    for i in range(n):
        sum += get_rand_num_slurm(lo, hi)
    return sum

@ct.lattice
def random_num_workflow(lo, hi):
    n = get_rand_sum_length(lo, hi)
    sum = add_n_random_nums(n, lo, hi) # sublattice
    return sum

id = ct.dispatch(random_num_workflow)(1, 3)
ct_result = ct.get_result(dispatch_id=id, wait=True)
sum = ct_result.result
print(sum)

```

### What should happen?

Should run to completion with no errors in the GUI and print an integer.

### Any suggestions?

My gut says that Covalent isn't reading the `username` attribute from `ct.executor.SlurmExecutor` and is instead looking at my `covalent.conf` where I have not defined `username`.

**Comment by jackbaker1001** [comment]
Having followed by hunch on this a little, it seems that nothing is being read from the executor being defined in the above and will only read data from the `covalent.conf` file.

**Comment by santoshkumarradha** [comment]
@jackbaker1001 are you using a remote covalent server or a server from where you are also instantiating the executor object (local covalent server)- might be an artifact of this - https://covalent.readthedocs.io/en/stable/developer/patterns/deployment.html#assigning-executors

**Comment by jackbaker1001** [comment]
I am using a local covalent server. I think the above is then in line with best practices no?

**Comment by santoshkumarradha** [comment]
yes it is! Okay then this is a bug.

**Comment by arosen93** [comment]
@jackbaker1001 --- did you happen to find a potential solution or workaround for this one? If not, I will also try to look into it next week sometime. Would be good to get this one patched.

**Comment by arosen93** [comment]
@jackbaker1001: This issue can be closed, as it is addressed in https://github.com/AgnostiqHQ/covalent/pull/1736

**Comment by arosen93** [comment]
@jackbaker1001: This issue can be closed, as it was addressed in https://github.com/AgnostiqHQ/covalent/pull/1736.
